package com.krillsson.sysapi.core.monitoring

enum class MonitorType {
    CPU_LOAD,
    CPU_TEMP,
    DRIVE_SPACE,
    DRIVE_READ_RATE,
    DRIVE_WRITE_RATE,
    MEMORY_SPACE,
    NETWORK_UP,
    NETWORK_UPLOAD_RATE,
    NETWORK_DOWNLOAD_RATE,
    CONTAINER_RUNNING,
    PROCESS_MEMORY_SPACE,
    PROCESS_CPU_LOAD,
    PROCESS_EXISTS,
    CONNECTIVITY,
    EXTERNAL_IP_CHANGED
}